name: channels-epg-grabber

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  epg-grabber:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run epg grabber
        run: cd epgs && python daddylive-channels-epg-grabber.py

      - name: Commit and push changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add epgs/daddylive-channels-epg.xml epgs/daddylive-channels-epg.xml.gz
          git diff --staged --quiet || git commit -m "Update channels epg"
          git push --force
      
      - name: Push changes to another repository
        env:
          TARGET_REPO: https://github.com/j-lich/uncle-fox-epg.git
          TARGET_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone --depth 1 $TARGET_REPO temp-target-repo
          cp epgs/daddylive-channels-epg.xml epgs/daddylive-channels-epg.xml.gz temp-target-repo/
          cd temp-target-repo
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add daddylive-channels-epg.xml daddylive-channels-epg.xml.gz
          git diff --staged --quiet || git commit -m "Update channels epg"
          git push origin $TARGET_BRANCH
