name: channels-epg-grabber

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  epg-grabber:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run epg grabber
        run: cd epgs && python daddylive-channels-epg-grabber.py

      - name: Commit and push changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add epgs/daddylive-channels-epg.xml epgs/daddylive-channels-epg.xml.gz
          git diff --staged --quiet || git commit -m "Update channels epg"
          git push --force
  
  push-to-uncle-fox-epg:
    needs: epg-grabber
    runs-on: ubuntu-latest
    steps:
      - name: Checkout generated XML from source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy XML file to temp directory
        run: |
          mkdir tmp_epg
          cp epgs/daddylive-channels-epg.xml tmp_epg/

      - name: Checkout Uncle-Fox-EPG repository
        uses: actions/checkout@v3
        with:
          repository: J-Lich/Uncle-Fox-EPG
          token: ${{ secrets.REPO_TOKEN }}
          ref: main
          path: uncle-fox-epg

      - name: Copy XML file into Uncle-Fox-EPG repo
        run: cp tmp_epg/daddylive-channels-epg.xml uncle-fox-epg/external/all.xml

      - name: Commit and push XML file to Uncle-Fox-EPG
        working-directory: uncle-fox-epg
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add external/all.xml
          git commit -m "Add new EPG XML file [CI skip]" || echo "No changes to commit"
          git push
      
